README.md
Fixed the link to Virgil in docs
=> Fixed docs link

src/engine/x86-64/X86_64Interpreter.v3
Didn't figure out how to write lambdas in Virgil. So I put the helpers above genSimdInstrs()
=> [simd]: Refactor v128 comparison instructions

ci/jvm/build-test-jvm.sh, ci/linux/build-test-x86.sh, ci/linux/build-test-x86_64.sh
Successful CI results in my repo: https://github.com/haoyu-zc/wizard-engine/actions/runs/5696426253/job/15441468121
=> Update CI scripts for specification tests

src/engine/v3/V3Interpreter.v3
Tested by `make v3i -j && bin/spectest.v3i -tk test/regress/simd/v128_extract_lane.bin.wast`
=> [v3i/simd]: Implement v128 extract_lane instructions

src/engine/v3/V3Interpreter.v3
Tested by:
```
make v3i -j && bin/spectest.v3i test/regress/simd/simd_splat.bin.wast
make v3i -j && bin/spectest.v3i test/regress/simd/simd_load_splat.bin.wast
```
=> [v3i/simd]: Implement v128 splat and load_splat

src/engine/v3/V3Interpreter.v3
Tested by:
` make v3i -j && bin/spectest.v3i -tk test/regress/simd/v128_replace_lane.bin.wast`
=> [simd/v3i]: Implement v128 replace_lane

src/engine/V3Eval.v3, src/engine/v3/V3Interpreter.v3
Tested by `make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_boolean.bin.wast`
=> [simd/v3i]: Implement boolean instructions

src/engine/x86-64/X86_64Interpreter.v3
- Factored out more tuple loops
- Created more generic routines
- Moved instructions around for better grouping
=> [fast-int]: Clean up code for v128 instructions

src/engine/BinParser.v3, src/engine/BpConstants.v3, src/engine/Instantiator.v3, src/engine/Module.v3, src/engine/Type.v3
This PR adds the continuation types (and its parsing) as part of implementing the stack switching proposal.
=> [stack-switch] Added Continuation type

src/monitors/LoopMonitor.v3
=> fixed an erroneous \n in LoopMonitor CSV output

test/spectest.main.v3
Sorry for missing this in the first PR!
=> Fix another case of possible failure for spectests for CLI usability

src/modules/wasi/x86-64-linux/WspOneModule-x86-64-linux.v3
=> added fd_datasync fd_seek fd_sync fd_tell sched_yield proc_raise to wasi

build.sh
Fixes warnings reported in #187
=> [build] Do not warn about pregen if host cannot run it

src/monitors/ModuleInstrumenter.v3
A possible fix to https://github.com/titzer/wizard-engine/issues/199 ?
=> Resolve issues with beforeFuncExec and beforeFuncReturn causing null reference issues 

src/engine/CodeValidator.v3, src/engine/Debug.v3, src/engine/Module.v3, src/engine/Sidetable.v3, src/engine/v3/V3Interpreter.v3, src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64Runtime.v3, src/engine/x86-64/X86_64Stack.v3
This PR unifies parts of suspension handling with exception handler
=> [stack-switching] Misc refactor involving suspension handling

src/modules/wasi/WspOneModule.v3, src/modules/wasi/x86-64-linux/WspOneModule-x86-64-linux.v3
Also, fix timestamps in the filestat record (depend on titzer/virgil#352) and update path_open to support more flags.
=> [wasi] Implement more functions

src/engine/Execute.v3, src/engine/v3/V3Interpreter.v3, src/engine/v3/V3Target.v3, src/engine/x86-64/X86_64Stack.v3, src/monitors/WhammMonitor.v3, src/wizeng.main.v3, test/unittest/ExeCallTest.v3, test/wasm-spec/SpecTestInterpreter.v3
This PR simplifies the stack return states.
=> [switch-switch] V3 refactor

src/engine/Debug.v3, src/engine/Execute.v3, src/engine/Module.v3, src/engine/Runtime.v3, src/engine/WasmStack.v3, src/engine/v3/V3Interpreter.v3, src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64Runtime.v3, src/engine/x86-64/X86_64Stack.v3, test/regress.failures.x86-64-linux
This PR implements `switch` in the fast-interpreter.
=> [stack-switching] `switch` implementation

src/monitors/WhammMonitor.v3
I _knew_ my report logic wasn't that efficient!!
=> Fix whamm report metric (copy/paste issue)

src/modules/wasi/WasiUtils.v3, src/modules/wasi/WspOneModule.v3, src/modules/wasi/x86-64-linux/WspOneModule-x86-64-linux.v3
=> [wasi] Return NOSYS error code for unimplemented functions
