titzer/wizard-engine

src/engine/Execute.v3, src/engine/Probe.v3, src/engine/v3/V3Interpreter.v3, src/engine/x86-64/X86_64Runtime.v3, src/monitors/BranchMonitor.v3, src/monitors/CallsMonitor.v3, src/monitors/CoverageMonitor.v3, src/monitors/LoopMonitor.v3, src/monitors/ProfileMonitor.v3, src/util/FuncMonitorUtil.v3, src/weerun.main.v3, test/unittest/DebugTest.v3, test/unittest/ProbeTest.v3
Also includes placeholder implementation for `V3Frame.caller()` (before we change the signature of `FrameAccessor.caller()` to support host functions too).
=> [monitors] Convert ProbeFrame to DynamicLoc and change probe signature

src/monitors/BranchMonitor.v3, src/monitors/CallsMonitor.v3, src/monitors/LoopMonitor.v3, src/monitors/ModuleMonitor.v3, src/monitors/MonitorOptions.v3, src/monitors/ProfileMonitor.v3, src/wizeng.main.v3, test/wizeng/calls3.wasm.out
Changes the old monitors to use the new `ModuleMonitor` interface.
=> [monitors] Use ModuleMonitor in Branch/Calls/ProfileMonitor

src/engine/CodeValidator.v3
- Added a call to checkSignature() in checkLane() so that all v128 instructions that check the lane index will now be correctly validated.
- Will factor out v128_extract_lane in the interpreter and finish implementing the rest instructions in future PRs.
=> [simd]: Fix signature check for v128 lane instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by ` make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i16x8_arith.bin.wast`
=> [simd/jit]: Implement simple i16x8 arithmetic operations

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i32x4_arith.bin.wast`
=> [simd/jit]: Implement simple i32x4 arithmetic operations

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i64x2_cmp.bin.wast`
=> [simd/jit]: Implement i64x2 comparison instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_f64x2_cmp.bin.wast`
=> [simd/jit]: Implement f64x2 comparison instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_f32x4_cmp.bin.wast`
=> [simd/jit]: Implement f32x4 comparison instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i32x4_arith2.bin.wast`
=> [simd/jit]: Implement more i32x4 arithmetic instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i8x16_arith2.bin.wast`
=> [simd/jit]: Implement more i8x16 arithmetic instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i16x8_arith2.bin.wast`
=> [simd/jit]: Implement more i16x8 arithmetic instructions

src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i64x2_arith2.bin.wast`
=> [simd/jit]: Implement i64x2_abs

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by:
```bash
function jit_test {
make -j
var_list=("i8x16" "i16x8" "i32x4" "i64x2" "f32x4" "f64x2")
for var in "${var_list[@]}"
do
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_${var}_arith.bin.wast
if [[ ${var:0:1} != "f" ]]
then
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_${var}_arith2.bin.wast
fi
done | progress
}
jit_test
```
=> [simd/jit]: Refactor unops using partial application

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by:
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_f32x4_pmin_pmax.bin.wast`
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_f32x4.bin.wast`
=> [simd/jit]: Implement more f32x4 arithmetic instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by:
```
make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_f64x2_pmin_pmax.bin.wast
make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_f64x2.bin.wast
```
=> [simd/jit]: Implement more f64x2 arithmetic instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by:
```bash
function jit_regress {
make -j
var_list=("i8x16" "i16x8" "i32x4" "i64x2" "f32x4" "f64x2")
for var in "${var_list[@]}"
do
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_${var}_arith.bin.wast
if [[ ${var:0:1} != "f" ]]
then
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_${var}_arith2.bin.wast
else
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_${var}.bin.wast
fi
done | progress
}
jit_regress
```
=> [simd/jit]: Factor out do_op2_x_x_xtmp() and do_c_op2_x_x_xtmp()

src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by:
```
make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i32x4_trunc_sat_f32x4.bin.wast
make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i32x4_trunc_sat_f64x2.bin.wast
```
=> [simd/jit]: Implement i32x4 trunc instructions

src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_f32x4_rounding.bin.wast`
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_f64x2_rounding.bin.wast`
=> [simd/jit]: Implement floating point rounding instructions

src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by:
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_int_to_int_extend.bin.wast`
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_conversions.bin.wast`
=> [simd/jit]: Implement simd type conversion instructions

src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by
```
make -j
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_load8_lane.bin.wast
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_load16_lane.bin.wast
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_load32_lane.bin.wast
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_load64_lane.bin.wast
```
The `visit_V128_LOAD_LANE` method's code is mostly borrowed from the `emitLoad` method in `SinglePassCompiler.v3` with a modified prologue and epilogue. Let me know if there are any hidden bugs or factoring out needed
=> [simd/jit]: Implement v128 lane loading instructions

src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by:
```
make -j
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_load_extend.bin.wast
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_load_zero.bin.wast
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_load_splat.bin.wast
```
=> [simd/jit]: Implement more V128 loading instructions

src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by:
```
make -j
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_store8_lane.bin.wast
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_store16_lane.bin.wast
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_store32_lane.bin.wast
bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_store64_lane.bin.wast
```
=> [simd/jit]: Implement v128 store_lane instructions

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_splat.bin.wast`
=> [simd/jit]: Implement v128 splat instructions

src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by 
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/v128_shuffle.bin.wast`
- `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/v128_swizzle.bin.wast`
=> [simd/jit]: Implement v128 shuffling and swizzling

src/engine/x86-64/X86_64SinglePassCompiler.v3
Tested by: `make -j && bin/spectest.x86-64-linux -tk -mode=spc test/regress/simd/simd_i64x2_extmul_i32x4.bin.wast`
=> [simd/jit]: Implement i64x2 extmul instructions

src/engine/V3Eval.v3, src/engine/Value.v3, src/engine/v3/V3Interpreter.v3
Tested by `make v3i -j && bin/spectest.v3i -tk test/regress/simd/v128.xor.bin.wast | progress`
=> [simd/v3i]: Implement v128 bitwise instructions

src/engine/Memory.v3, src/engine/Trap.v3, src/engine/v3/V3Interpreter.v3, src/engine/v3/V3Memory.v3, src/engine/x86-64/X86_64Memory.v3, src/modules/wasi/WspOneModule.v3, src/modules/wasi/x86-64-linux/WspOneModule-x86-64-linux.v3, src/monitors/MemoryMonitor.v3, src/util/Decoder.v3, test/unittest/ExeTest.v3, test/unittest/MemoryTest.v3, test/unittest/ModuleBuilder.v3
This moves most of the memory functionality into the base class `Memory.v3` and makes use of the new off-heap `Range<byte>` feature to targets that use `mmap`ed memory to also use Ranges. That saves code and moves more into the safe core Virgil language. It also makes use of some new utility methods in Virgil's libraries to do multi-byte store/load using layouts underneath, which speeds up the `x86-linux` target anywhere from 2-7%.
=> Refactor memory to use Range<byte>

src/engine/V3Eval.v3, src/engine/v3/V3Interpreter.v3
Tested by:
```
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_i64x2_arith2.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_i32x4_arith2.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_i16x8_arith2.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_i8x16_arith2.bin.wast
```
=> [simd/v3i]: Implement more integer arithmetic instructions

src/engine/Value.v3, src/engine/v3/V3Interpreter.v3
Used bit manipulation instead of arrays as I did in my first attempt.
As discussed, the unboxing step is not necessary. But removing it involves factoring out `doLoad`. Will create a new PR for this later.
Tested by
```
make -j && bin/spectest.x86-linux -tk test/regress/simd/simd_load64_lane.bin.wast
make -j && bin/spectest.x86-linux -tk test/regress/simd/simd_load32_lane.bin.wast
make -j && bin/spectest.x86-linux -tk test/regress/simd/simd_load16_lane.bin.wast
make -j && bin/spectest.x86-linux -tk test/regress/simd/simd_load8_lane.bin.wast
```
=> [v3i/simd]: Implement load_lane instructions

src/engine/V3Eval.v3, src/engine/v3/V3Interpreter.v3
Tested by:
```
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_f32x4.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_f32x4_pmin_pmax.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_f64x2.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_f64x2_pmin_pmax.bin.wast
```
=> [v3i/simd]: Implement min, max, abs instructions for f32 and f64

src/engine/V3Eval.v3, src/engine/v3/V3Interpreter.v3
Tested by
```
make -j && bin/spectest.x86-linux -tk test/regress/simd/simd_i16x8_extadd_pairwise_i8x16.bin.wast
make -j && bin/spectest.x86-linux -tk test/regress/simd/simd_i32x4_extadd_pairwise_i16x8.bin.wast
```
Added two new helpers.
=> [v3i/simd]: Implement extended pairwise integer addition

ci/jvm/build-test-jvm.sh, ci/linux/build-test-x86.sh, ci/linux/build-test-x86_64.sh
We need to add `-y` since menhir depends on other libraries, and opam asks for our permission to proceed.
Successful CI run in my repo: https://github.com/haoyu-zc/wizard-engine/actions/runs/6894577687/job/18756696731
=> [ci] Update to include menhir and its dependencies

src/engine/v3/V3Interpreter.v3
Tested by:
```
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_store64_lane.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_store32_lane.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_store16_lane.bin.wast
make v3i -j && bin/spectest.v3i -tk test/regress/simd/simd_store8_lane.bin.wast
```
=> [simd/v3i]: Implement v128 store_lane

src/engine/CodeValidator.v3, src/util/ErrorGen.v3
This PR adds continuation type checking when validation the handler table for `cont.resume` and `cont.resume_throw`.
=> [typed-cont] Stricter check for continuation signature in cont.resume

src/monitors/BytecodeProfilingMonitor.v3
Both `CountProbe` and `CountMoreProbe` are intrinsified by the JIT, so this should be more efficient.
=> [monitors] Use CountProbe and CountMoreProbe for fuel calculation

src/engine/Opcodes.v3
Updated `parseName` to handle `ref.test null` and `ref.cast null` without excessively eating spaces for opcodes which do not need it. I need it to parse opcodes Whamm probes as there can be spaces between the opcode mnemonic and the predicate separator.
=> Remove excessive spaces for parsing opcode mnemonics

src/engine/Debug.v3, src/engine/x86-64/V3Offsets.v3, src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64PreGenStubs.v3, src/engine/x86-64/X86_64Runtime.v3, src/engine/x86-64/X86_64Stack.v3
This PR implements `resume_throw`. It also cleans up the previous stack switching code + stack stubs in preparation for JIT implementation.
=> [stack-switching] `resume_throw` Implementation

src/modules/wasi/x86-64-linux/WspOneModule-x86-64-linux.v3
The Unix file descriptor was returned instead of the user-level file descriptor.
=> WASI: fix path_open

src/engine/v3/V3Interpreter.v3
Instruction tracing for `V3Interpreter` has been moved to probes, so `traceStep` is unused. This PR removes it.
=> [misc] Cleaned up unused function `traceStep`

src/engine/x86-64/X86_64Interpreter.v3, test/regress/big/br_on_cast99.wast, test/regress/big/ref_cast99.wast, test/unittest/ExeTest.v3
=> [gc] Fast interpreter should use curpc to restore start of instruction instead of interior bytecode pointer

src/engine/BytecodeIterator.v3, src/engine/CodePtr.v3, src/engine/CodeValidator.v3, src/engine/Module.v3, src/engine/Opcodes.v3, src/engine/compiler/SinglePassCompiler.v3, src/engine/x86-64/X86_64Interpreter.v3, src/util/OpcodeMap.v3, src/util/WasmAsm.v3, test/unittest/BinParserTest.v3, test/unittest/BytecodeIteratorTest.v3, test/unittest/CodeValidatorTest.v3, test/unittest/ControlStackTest.v3, test/unittest/DebugTest.v3, test/unittest/ExeCallTest.v3, test/unittest/ExeProbeTest.v3, test/unittest/ExeTest.v3, test/unittest/ModuleBuilder.v3, test/unittest/OutlineTest.v3, test/unittest/ProbeTest.v3, test/unittest/SidetableTest.v3, test/unittest/WasmStackTest.v3, test/unittest/x86-64-linux/X86_64LinuxExeTest.v3
Does not yet include the run-time dispatch table building and use in the Fast interpreter, but builds and passes the tests I can run (I'm not set up for JVM tests at present).
=> Add support for longer (14 bit) opcodes.

src/modules/wali/x86-64-linux/WaliCheck.v3, src/modules/wali/x86-64-linux/X86_64LinuxWaliModule.v3
Removed `ArgType` enum to reduce activations.
=> [wali] Removing generic argument type on WaliCheck

test/regress.failures.x86-64-linux
This PR removes canonicalization tests from `regress.failures.x86-64-linux` as they pass now.
=> [stack-switching] Removed passing canonicalization tests from `regress.failures.x86-64-linux`

src/engine/compiler/MacroAssembler.v3, src/engine/compiler/SinglePassCompiler.v3, src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64MacroAssembler.v3, src/engine/x86-64/X86_64Runtime.v3, src/engine/x86-64/X86_64SinglePassCompiler.v3, src/engine/x86-64/X86_64Stack.v3
This refactor changes the runtime stack's `rsp` to point to the interpreter code's return address, making its `rsp` placement consistent with suspended stacks.
=> Running stack's `rsp` points to return address instead of interpreter frame

src/engine/WasmStack.v3, src/engine/v3/V3Interpreter.v3, src/engine/v3/V3Target.v3, src/engine/x86-64/V3Offsets.v3, src/engine/x86-64/X86_64Interpreter.v3, src/engine/x86-64/X86_64Runtime.v3, src/engine/x86-64/X86_64Stack.v3
This PR enables stack walking to continue onto parent stacks for the stack-switching extension, eliminating the need for `%ret_throw` when handling exceptions.
=> [refactor] Improved stack walking logic

src/util/Whamm.v3
There is a bug if we have the following:
```
(func "wasm:opcode:i32.const  ($15(fid, pc), local0)" (param i32 i32) ...)
```
This probe has a type bound on `local0`. We only have a match if the `local0` is, in fact, an `i32`. If it's not an `i32`, we don't have a match and the probe won't be inserted. This logic is done correctly, the probe isn't inserted...but the static allocation function is still called during parameter parsing. This means that we allocate memory for a probe that we'll never use since it's not inserted.
This PR fixes this issue through lazily performing these calls if other parameter preparation results in a match.
=> Only perform calls in match rules if other params result in a match

src/bytecode/.gitignore, src/bytecode/CanonicalDefs.v3
We need type annotations for u32 lits and infix for comparisons. Also updated the gitignore so it's easier to push changes from the submodule in the cbd repo
=> [cbd] updated defs

src/SpectestMode.v3, src/monitors/Monitor.v3, test/wasm-spec/SpecTestInterpreter.v3
This PR adds monitor hooks to spectest execution. This is in preparation for adding memory inspection related probes during stack-switching spectests for more stack/continuation memory integrity coverage during testing.
=> [monitors] Added monitor hooks to `SpecTestInterpreter`

src/engine/SigCache.v3, src/modules/HostModuleBuilder.v3, src/modules/wali/x86-64-linux/WaliModule.v3, src/util/HostAdapters.v3
With this PR wizard should have all WALI passthroughs implementation similar to WAMR:
```
- read
- write
- close
- stat
- fstat
- lstat
- poll
- lseek
- mprotect
- ioctl
- pread64
- pwrite64
- access
- pipe
- select
- msync
- madvise
- dup
- dup2
- nanosleep
- alarm
- setitimer
- getpid
- socket
- connect
- accept
- sendto
- recvfrom
- shutdown
- bind
- listen
- getsockname
- getpeername
- socketpair
- setsockopt
- getsockopt
- fork
- wait4
- kill
- uname
- flock
- fsync
- fdatasync
- ftruncate
- getdents
- getcwd
- chdir
- fchdir
- rename
- mkdir
- rmdir
- link
- unlink
- symlink
- readlink
- chmod
- fchmod
- chown
- fchown
- umask
- getrlimit
- getrusage
- sysinfo
- getuid
- getgid
- setgid
- geteuid
- getegid
- setpgid
- getppid
- setsid
- setreuid
- setregid
- getgroups
- setgroups
- …
```
=> [wali] Add passthroughs implementation
